#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Executando yarn run lint:check..."
echo "Em caso de erros ou warnings, rode o comando yarn run lintfix e corrija a lista abaixo antes de realizar o commit."

yarn run lint:check

