#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Executando Prettier..."
npm run format

echo "Executando npm run lint:check..."
echo "Em caso de erros ou warnings, rode o comando npm run lint:fix e corrija a lista abaixo antes de realizar o commit."

npm run lint:check

